### ISSUE TITLE
Offer report

### ISSUE THREAD

**Issue by orbardugo** [erezam/DNA-PRIMER-BUILDER#9]
##Explanation:

Write project Offer report, according to website's commands.

##Checklist:
- [x] make market survey
- [x] Requirements table
- [x] Risk Management
- [x] Documenting reading
- [x] Architecture diagram
- [x] Problem Description
- [x] Description of the solution

**Comment by erezam** [comment]
[טופס הצעה.pdf](https://github.com/erezam/DNA-PRIMER-BUILDER/files/1547419/default.pdf)
